### ISSUE TITLE
MiamiDX

### ISSUE THREAD

**Issue by eispic** [kouts/best-classic-wb#10]
The MiamiDX programme cannot be started.

**Comment by kouts** [comment]
I cannot reproduce this one @eispic.
If you are running WinUAE Miami cannot start because WinUAE has its own TCP/IP stack running in the background.

![image](https://github.com/kouts/best-classic-wb/assets/2233663/4b44c621-fc19-4977-b686-51767603a6ad)

**Comment by eispic** [comment]
Ok. My assign command for MiamiDx in the "user-startup" was not correct. I had to adjust it in SYS:Internet/MiamiDx.
