### ISSUE TITLE
My Impressions, please update some Programs

### ISSUE THREAD

**Issue by eispic** [kouts/best-classic-wb#2]
I am from Germany and my English is not so good, so I had this message translated with google. My impressions about BestClaasicWB 2.1.7 and V2.1.8 are the following.
I installed BestClassicWB 2.1.7 fresh on an AmigaOS3.2.2.1 and then installed and updated a lot of programs like Snoopdos 3.11, WHDLoad 19.0 Beta, ClearRam V1.01, MMULib 47.6.2, SwazInfo 18B, LoadModule 45.18, and many more.
Then I saw the update to BestClassicWB 2.1.8, installed it over V2.1.7 and realized that programs (Snoopdos, WHDLoad, LoadModule) were overwritten with the version in BestClassicWB 2.1.7. That is stupid. Couldn't you create an additional package where only the BugFixed are installed? Like a small update pack from V2.1.7 to V2.1.8.
Where can you get the ideas, at Gihub ? I think that many would help with this project.
Maybe also create a Discord channel

Can you update/add the following for the next update:
Snoopdos 3.11 http://aminet.net/package/util/moni/SnoopDos
ClearRam http://aminet.net/search?name=clearram&path[]=util/misc
MMULib 47.6.2 http://aminet.net/search?name=mmulib&path[]=util/libs
SwazInfo 18b http://aminet.net/search?name=swazinfo&path[]=util/wb
LoadModule 45.18 http://aminet.net/search?name=loadmodule&path[]=util/boot
SysInfo 4.4 http://aminet.net/search?name=sysinfo&path[]=util/moni
KingCon 1.3 http://aminet.net/search?name=kingcon&path[]=util/shell
Scalos 1.2b http://aminet.net/search?name=scalos&path[]=util/wb
MagicMenu 2.35 http://aminet.net/search?name=magicmenu&path[]=util/wb

**Comment by kouts** [comment]
Hello @eispic, thanks for your comments.
I'll see if I can update some of them but I have no immediate plans to do so as the ones currently in place are working fine.
For me, stability is a priority over having the newest version.

- MagicMenu 2.35 - I found that it is slow in my A1200/030
- LoadModule is part of the AmigaOS 3.2.2.1
- I won't be introducing Scalos, KingCon, SysInfo, ClearRam into the project.
You can always install them after the initial intall.

Thank you
