### ISSUE TITLE
Protection Bit (from English Amiga Board)

### ISSUE THREAD

**Issue by eispic** [kouts/best-classic-wb#22]
I installed to PFS 3 partition...The following files need the executable protection bit set in your latest BestClassicWB release...

C:FBlit
C:FText
C:FPPrefs

Without this fix, it will not boot. Now you know the files to fix, hopefully you can now sort the problem.

**Comment by eispic** [comment]
Second bug is I note you replaced TinyMeter with Newmeter... Newmeter CPU usage gauge is throttling the CPU... I found to fix this problem, uncomment IDLETASK tooltype in NewMeter's icon (WBStartup) drawer.

**Comment by kouts** [comment]
Thanks @eispic I have uncommented the `IDLETASK` tooltype in NewMeter and added the executable protection bit in the installation script for:
```
C:FBlit
C:FText
C:FPPrefs
```

Let me know if that works.

09d347513a4ae75499f5183a7bf09203944b99b8
b4eceb745753e8befb9abe6cd61abc04221bfc3c
