### ISSUE TITLE
prism2.device

### ISSUE THREAD

**Issue by eispic** [kouts/best-classic-wb#9]
After the Workbench has been started and I have started SnoopDos, I see in the SnoopDos window that an attempt is being made to load the prism2.device file from the Devs:Network folder and that it is permanently loaded. This file does not exist. Why is the file being loaded? This problem is not present in BestClassicWB 2.1.7, only in versions 2.1.8 and 2.1.9.

**Comment by kouts** [comment]
Thanks for the report @eispic, this is now fixed with 3289bc5
